### ISSUE TITLE
Quote chars broken on US-International keyboard

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#4]
# Updated issue

**Steps to reproduce:**

1. Use [international keyboard with dead keys](https://www.scottseverance.us/html/keyboard/win_intl_altgr/)
1. Use Linux server
1. Type ' or “ on macOS client
1. Type ' or “ on Windows client

**Expected:** 

The ' and “ chars are typed on the client.

**Actual:**

On the Linux server,  it all goes well: ' (the quote, 0x27) and " (the double quote, 0x22)

On the Mac client: ´ (the slanted quote, 0xB4) and ¨ (the trema, 0xA8)

On the Windows client: nothing for the single quote and ¨ (the trema, 0xA8)

# Original issue
**Imported issue:**
- Author: ambros (Google user)
- Date: 2009-03-01 00:00:00
- Legacy ID: 13

To reproduce:  
1. set your keyboard as US-International keyboard, language English  
2. open notepad  
3. type apostrophe or quote  
4. type space  
(nothing happens)  

**What is the expected output? What do you see instead?**  
Apostrophes or quotes are not displayed.  

**What version of the product are you using? On what operating system?**  
Tested in two different confits:  
- Windows XP Media Center (host) with Vista 32b and with Mac OSX (clients)  
- Windows 7 64b (host) with Windows Vista 32 (client)  

Same behavior.  

**Please provide any additional information below.**  
Microsoft Comfort Keyboard 2000 v1.0

**Comment by jmaynier** [comment]
+1

**Comment by firekraag** [comment]
+1.
Tested: Server = OS X, Client = Debian. `'`+`SPACE` enters a quote (as intended) but `'`+`e` does nothing (should enter é)

**Comment by JossiEnd** [comment]
I tried following all the post and referenced posts and i think this is the place to mention the issue that i'm still not able to use either ' or " on the client side of Synergy. My apologies if this is the incorrect place. 

**Issue:**
1. set your keyboard as US-International keyboard, language English
2. open notepad
3. type apostrophe or quote
4. type space
(nothing happens)

**What is the expected output? What do you see instead?**
Apostrophes or quotes are not displayed on the client side (host side is fine)

**What version of the product are you using? On what operating system?**
Client and host have the same OS, keyboard layout and Synergy version:
OS: Windows 10 Pro (64bit)
Synergy: 1.7.6
Keyboard: United States-International

**Please provide any additional information below.**
é-ë, á-ä, í-ï, etc. are working fine on both client and host side.

**Comment by noboruma** [comment]
+1
Tested: Server = Windows 7 (SP1), Client = Debian 8 (Jessie), both versions 1.8.2.

**Comment by pretyman** [comment]
+1 
Client = OSX 10.11
Server = OSX 10.11
Version: 1.8.2-stable-36cd521

**Comment by nlyan** [comment]
Anyone got any feedback wrt this bug on v1.8.3 ?

**Comment by noboruma** [comment]
Still not working under v1.8.3
Tested: Client = Windows 7 (SP1), Server = Debian 8 (Jessie), both versions 1.8.3.
(somehow àìòè are working properly but that seems to be the only ones)

**Comment by JossiEnd** [comment]
I can also confirm that its not working on version: 1.8.3-rc2-89c9c58.

**What version of the product are you using? On what operating system?**
Client and host have the same OS, keyboard layout and Synergy version:
OS: Windows 10 Pro (64bit)
Synergy: 1.8.3-rc2-89c9c58
Keyboard: United States-International

**Comment by nashermb** [comment]
### Still not working
V 1.8.3-stable-db9181b
Client & Server on Window 10 Pro (64bit)

**Comment by sirpedro95** [comment]
It's working now on v1.8.4, but now problem to quotes (").

**Comment by noboruma** [comment]
No progress on my end..
Client: synergy-master-stable-1796150 windows 7 pro (SP1)
Server: synergy-master-stable-1796150 Debian 8.0
@sirpedro95 what is your config?

**Comment by sirpedro95** [comment]
@noboruma both of layout US International

Server -> Windows 10 64bits
Client -> macOS Sierra

~ ´ and ç (Brazil) is working perfect, but ' is not working.

**Comment by komodin** [comment]
I still have the same problem on the latest stable version.
Server > macOS Sierra
Client > Windows 10 64bits

**Comment by Crytiqal** [comment]
Issue from OP still exists.

**Issue:**

1. set your keyboard as US-International keyboard, language English
2. open notepad
3. type apostrophe or quote
4. type space (nothing happens)

**What is the expected output? What do you see instead?**
Apostrophes or quotes are not displayed on the client side (host side is fine)

**What version of the product are you using? On what operating system?**
Client and host have the same OS, keyboard layout and Synergy version:
OS: Windows 10 Pro (64bit)
Synergy: 1.8.6
Keyboard: United States-International


Shouldn't the key press being send by the server be interpreted exactly the same on the client if they both use the same layout?

**Comment by yupi2** [comment]
@Crytiqal The key sending stuff is very generic and probably doesn't have handling for many edge-cases like this.

**Comment by Crytiqal** [comment]
United States-International is an edge-case? You must be joking.

**Comment by yupi2** [comment]
@Crytiqal Kind of is sadly.

**Comment by Crytiqal** [comment]
Except everyone outside the US uses the International layout?

**Comment by yupi2** [comment]
@Crytiqal That's why it's sad that it's an edge-case. I'll try to find a solution for it soon it's not something I personally use so it's not top priority for me. (note: I'm not a part of symless inc.)

**Comment by Crytiqal** [comment]
@yupi2 Sorry, I guess I misunderstood. I thought an edge-case meant something that is at the end of most common cases, a rarity.

**Comment by orgasmix** [comment]
​@​Crytiqal Think he meant an edge-case from the programmer's point of view, like a misdesigned if branch, not an edge use-case

**Comment by vegarab** [comment]
**Issue:**
1. set your keyboard as US-International keyboard, language English
2. open notepad
3. type apostrophe or quote
4. type space (nothing happens)
 **What is the expected output? What do you see instead?**
Apostrophes or quotes are not displayed on the client side (host side is fine)

**What version of the product are you using? On what operating system?**
Client and host have the same OS, keyboard layout and Synergy version:
OS: Windows 10 Pro (64bit)
Synergy: 1.8.6
Keyboard: United States-International

What a piece of garbage! Just bought this piece of software because "Programmers love Synergy!". Have you EVER met a programmer that doesn't need "  and '? This is a two year old bug - I want my money back.

**Comment by brunosantosnasajon** [comment]
Just bought the program a few days ago and also having the same issue. As a software developer, not being able to use single quotes is a huge problem. Will ask for my money back as this software is useless to me.

**Comment by Sidesplitter** [comment]
A temporary fix is changing your layout from US-International to US, this allows me to to at least type quotes. The bad side is that I cannot type is that I cannot type an 'ë' for example.

**Comment by orgasmix** [comment]
> A temporary fix is changing your layout from US-International to US, this allows me to to at least type quotes. The bad side is that I cannot type is that I cannot type an 'ë' for example.
Which is the whole point of using us-intl in the first place

**Comment by marcelloma** [comment]
Any ETA for this fix? I really liked synergy but lacking ' and " is just unbearable for anything programming related. As mentioned by other people changing to US is out of question. Will sadly have to ask for a refund as well. despite really wanting to use this.

**Comment by walker0643** [comment]
I would really like to see this get fixed as well. Given that synergy is advertised as an app for programmers I would like to see this bug given high priority. It hurts programmers as well as anyone speaking in any language that uses accented characters.

**Comment by unicorn777** [comment]
Same problem here with version 1.8.7 (server Ubuntu 16.04 , client Windows 10)

**Comment by jaoord** [comment]
This is still confirmed in Windows 10. (client & server).

**Comment by giammin** [comment]
still here: 
synergy:1.8.8
windows 10 version 1703 build 15063.296
macos sierra 10.12.4

**Comment by matheuscmpm** [comment]
OP issue still exists. 

Synergy Version: 1.8.8-stable-25a8cb2
Server: Windows 10
Client: OSX

Any kind of estimated date to fix this issue? This is really annoying... since I am a developer, I do use quotes quite a lot.

**Comment by giammin** [comment]
I can't believe that a software you actually pay for has so many bugs that are resolved and then show up over and over again

and can't believe that those bug remains without a response from the developer team for years

**Comment by brunobr** [comment]
Same issue, stop using Synergy for a long time because of this, because as a developer the missing quotes are a big deal to me. Downloaded again today imagining the issue would be long gone, guess I will stop using again... too bad I didn't asked for my money back the first time it happened...

Working: á,ä,é,ë,í,ï,...,ç
Not Working: ' and "

Synergy Version: 1.8.8-stable-25a8cb2
Server: Windows 7 Pro SP1
Client: macOS Sierra (10.12.5)

**Comment by giammin** [comment]
For some version it worked. Maybe the previous version.
The last version 1.8,8 reintroduced some old bugs

**Comment by Canule** [comment]
Same here:
Win10 (US-Int) » Win10 (US-Int)
Win10 (US-Int) » 7(US-Int)

**Comment by acekrystal** [comment]
Same problem here.
I do programming and chatting, but I can't even type English as this sentence is already impossible as it contains a ' in "can't". (And now also two "quotes")

I can't type the **'** and the **"**.

Tried lots of different solutions like making a config file with altgr = shift, but it all didn't work.
I can't remember having this problem in the past...

But I guess Synergy is never gonna fix this problem as it moved on to Synergy 2 leaving everyone with a "live-time" license for synergy in the cold. Such a waste of a potential good program.

**Comment by rutgervandenberg** [comment]
At the risk of redundancy, I'm having the same problem. This makes synergy useless for coding

**Comment by amartins** [comment]
@nbolton This issue was fixed on Synergy 2?

**Comment by amartins** [comment]
@nbolton This issue was fixes on Synergy 2?

**Comment by amartins** [comment]
@nbolton Unfortunately yes. The apostrophes and quotes are still not working in latest 1.10 release. The Server & Client are macOS High Sierra and I'm using U.S. International - PC keyboard on both machines...

**Comment by nbolton** [comment]
Well darn it.

**Comment by rwuwon** [comment]
US International seems to work differently across macOS and Linux and Windows. While Linux has the Windows-style US International (with dead keys), it also has the AltGr version (which I know there is separate issue open for). macOS on the other hand seems to combine the two into a blend, with the default English input having an inbuilt AltGr function.

At risk of confusing things further, I noticed something possibly interesting and hopefully helpful:

Client: Win10 under VirtualBox in Fedora 28
Server: macOS 10.13.5
Synergy: v2.0.0-stable (compiled in macOS, and via the System repo for Fedora)

On the VirtualBox Win10 side: Enable United States-International
macOS: Enable U.S. International P.C.
Apostrophe (') will now *only* come through the Windows VM client if you type it twice in a row. Characters such as é won't come through - this seems to reflect the aforementioned behaviour.

**However:**
Try now disabling U.S. International P.C on the server end while leaving it enabled in client.

For me, this seems to work as far as dead keys go - is it the same for those using bare-metal Windows while having US International enabled on *only* the client side? If so, it could be useful as a semi-workaround even if it's clumsy and require frequent switching at the server end.

It seems to me that US International is less likely to work if it's enabled on both ends, and it's worth checking to see if results are any better when it's **only** enabled at the client end. Let me know if this is useful or not. Apologies if this is specific to only v1.x, but I don't think enabling US International on both ends at the same time helps.

**Comment by amartins** [comment]
@rwuwon Thanks for the heads up. What I did to fix the problem was:

1. Enable US keyboard on both macOS 10.13.6 client & server;
2. Restart Synergy.app on both machines;
3. The apostrophes and quotes start to work on the client machine; 
4. Revert to U.S. International - PC and bingo! " & ' working! 👍

**Comment by nbolton** [comment]
Fixed by #6616

**Comment by Venalyo** [comment]
Still have the issue with Synergy `1.12.0-stable-cb8064e8` between two Windows 10 computers, both using US-Int layout: apostrophes and quotes don't do anything.

**Comment by giammin** [comment]
me too. this bug continue to arise regularly

**Comment by pjrm** [comment]
This bug still happens on 1.14.0-stable-67d824b8.

There's any ETA for fixing this recurrent issue? Without the usage of single/double quotes, I can't use synergy.

**Comment by castro-andres** [comment]
Hello, I still have the same problem. Arch Linux like a server and Mac like a client both in english keyboard

**Comment by lucawen** [comment]
same here... happening with Arch linux server and Mac client. This is the output that I am receiving: ¨¨¨

**Comment by nbolton** [comment]
Referenced from: https://forums.symless.com/topic/6416-quotes-and-double-quotes-on-clients-when-using-international-keyboard-layout-with-dead-keys

**Comment by joepreludian** [comment]
Just a small contribution here. I'm using ver 3.0.80.1-rc3 between two macbooks Sonoma and I faced the same problem. I'm using a Brazilian layout for US mac keyboard.

The steps I took was inspired by @amartins, with a small change.
* Into the controlled computer, I added the `us-international` keyboard.
* Restarted the agent on the controlled machine. 
* Sorted. =)

When changing back to BR layout it worked without problems.
No need to add a second layout on the server side.

Thank you!

**Comment by nbolton** [comment]
> I'm using ver 3.0.80.1-rc3 between two macbooks Sonoma and I faced the same problem.

Thanks for confirming this is still a problem.

**Comment by cidico** [comment]
hi there! I just started using the Deskflow app and my server is a Win11 machine and the client is a W11 machine as well...
It seems odd that from time to time the " and '  chars stop being sent to the client.
It's working just fine on the server.

**Comment by nbolton** [comment]
> It seems odd that from time to time the " and ' chars stop being sent to the client.

Are you seeing #8168?

**Comment by cidico** [comment]
@nbolton I was not aware, sorry! I will post some info there! :)

**Comment by camilohollanda** [comment]
The issue still exists when mac to mac sharing

**Comment by sithlord48** [comment]
We are aware (that is why the bug is still open) May work right on wayland only

**Comment by TheRedfoox** [comment]
Is there a progress on this problem?

**Comment by sithlord48** [comment]
If we have progress it will be reported.
