### ISSUE TITLE
Mouse is slow on a high DPI Windows client

### ISSUE THREAD

**Issue by JohnSully** [deskflow/deskflow#4245]
When using synergy with a standard DPI server and a High DPI client the mouse is extremely sluggish.  When using a mouse connected directly to the client machine the speed of the pointer is normal.  Changing the pointer speed on the client has no effect.  Changing on the server does but makes the mouse much too fast on the server machine.

My guess is the mouse deltas are not being adjusted for DPI.

This is on both windows client and server (windows 8.1)

**Comment by jtmcdole** [comment]
I hit this today with a HDPI laptop client and a linux server.  Quick work around is to just bump the dpi higher on the mouse using the built in buttons. Would be nice to not have to do that tough.

**Comment by XinyuHou** [comment]
@jtmcdole @JohnSully 
Could you try this workaround please?
1. Go to Synergy installed directory
2. Right click synergyc.exe
3. Click Compatibility tab
4. Click Change settings for all users
5. Change Compatibility mode to Windows 7
6. Tick Disable display scaling on high DPI settings

**Comment by XinyuHou** [comment]
> Operating Systems
> 
> Server: Windows 10
> Client: Windows 10
> 
> Synergy Version
> 
> 1.8.4
> 
> Steps to reproduce bug
> 
> Setup Windows 10 server on a normal DPI computer.
> Connect with a high DPI Windows 10 client
> Move mouse to high DPI client, mouse moves slower than it used to
> Other info
> 
> This problem started occurring on Synergy 1.8.4. It makes Synergy very difficult to use, to the point I am no longer using it.

**Comment by XinyuHou** [comment]
> I've got a variation to this issue as well:
> 
> Operating Systems
> 
> Server: Windows 10 -> 5k High DPI Monitor
> Client: MacOS Sierra -> 5k iMac High DPI Monitor
> 
> Synergy Version
> 
> 1.8.4
> 
> Steps to reproduce bug
> 
> Setup Windows 10 server on a High DPI computer.
> Connect with a high DPI MacOS Sierra client
> Move mouse to high DPI client, mouse moves twice as fast as the host machine's mouse speed.
> 
> My back of the napkin math says that the high DPI host isn't scaling the mouse rate correctly for the client's DPI resolution considering the host's DPI/rate.

**Comment by fuzzzerd** [comment]
This appears to be happening again in 2.0. 

Server: Win 10 @125%
Client: Win 10 @200%

Mouse moves very slowly on client screen.

**Comment by doublerebel** [comment]
I also experience this with 2.0.5.

Server: Mac OS 10.12.6 (Mac mini with 1920x1080 screen)
Client: Win 10 @175% (Surface Pro 4)

Mouse moves very slowly on client screen.

**Comment by RayKoopa** [comment]
Why has this been closed? Synergy is still having this issue. If you connect from a 100% DPI server to a 200% DPI client, the mouse is half as fast, and vice versa. It's pretty unusable.

**Comment by nbolton** [comment]
@RayKoopa Have you tried v1.10.2?

**Comment by RayKoopa** [comment]
Yes, both server and client are on 1.10.2-stable-8c010140

**Comment by nbolton** [comment]
Ah, yeah, we're using an old version of Qt, so DPI on the GUI is an issue. Strange to hear that you're still having DPI issues on Windows. I'll reopen this issue in that case.

**Comment by RayKoopa** [comment]
Thanks, and sorry for the rude entrance of mine :o
If you're stuck with the Qt version, the only real issue is the window size - it should be doubled on 200% which I do manually by resizing it, then everything looks correct enough. However, the About dialog is unresizable.

**Comment by neworld** [comment]
I have the same issue with 0.10.3. The server is in HDPI, and the client is in normal DPI. 

Maybe config option to adjust mouse speed scaling could solve our problems? For example:

```conf
section: screens
	neworld:
		...
	DESKTOP-FPMDBS9: ; my secondary PC
		...
		mouseSpeedScaling = 0.75 ; I could fine tune this setting until I got exactly match. 
end
```

Issue author could use >1 values to increase speed.

**Comment by neworld** [comment]
I managed to adjust mouse speed by recompiling the application. Patch file: https://github.com/neworld/personal-aur-synergy/blob/master/trunk/adjust_low_dpi_mouse_speed.patch

2 times slower mouse speed makes much difference. 

My setup:

- Host: 290 DPI
- Guest: 96 DPI

**Comment by RayKoopa** [comment]
Something like that, but Synergy should be able to automatically detect the DPI settings and scale accordingly.

**Comment by Quadratball** [comment]
Hell this makes Synergy unuseable :( I loved this tool.
Replaced my FullHD-TV with a 4K-TV and running it on 300%. Mouse on TV-Screen is very slow now.
Running 1.11.0 Basic on Server and Client.

**Comment by adam-lynch** [comment]
I just signed up and it's the same for me. HDPI Windows client. It makes it pretty unusable

**Comment by roughwood** [comment]
Jumping in to share that I'm having this issue too. Server has a 1440p monitor at 100% scaling and I have a client with a 4k screen with 200% scaling. Mouse is about half as fast on the client. Very distracting and annoying.

**Comment by beerMT** [comment]
+1 just purchased this tool and have same issue when moving between new MBP and Windows Surface.

**Comment by samal84** [comment]
Getting this too on 1.11 between a win 10 desktop with a standard definition screen that is the server and a win 10 laptop with a high dpi screen that is the client. Mouse is super slow on the laptop.

**Comment by empereor** [comment]
Also getting this on 1.11.0, same as above; connecting on Windows 10 desktop with a standard definition screen that is the server and a Windows 10 laptop with a high dpi screen that is the client. Mouse is super slow on the laptop.

I would think this a fairly common config. Making Synergy unusable for me.

**Comment by empereor** [comment]
Just thought I'd note; also having the same issue going from the same Windows 10 server to a MacBook Pro client, both running 1.11.0.

**Comment by nbolton** [comment]
@Jnewbon I'm sure we'd fixed this. Perhaps it regressed? Or maybe it's a new issue?

**Comment by neworld** [comment]
@nbolton, This is a very old problem newer fixed. The problem occurs if machines are using different DPI. For example, my server node uses ~300 DPI display while the guest node uses ~80 DPI. A small movement in the HiDPI machine means 3.75 times bigger movement on the guest. For my self I fixed by adjusting the code with the following diff:
```
diff --git a/src/lib/server/Server.cpp b/src/lib/server/Server.cpp
index 2d7a2da..bc11104 100644
--- a/src/lib/server/Server.cpp
+++ b/src/lib/server/Server.cpp
@@ -1911,7 +1911,10 @@ Server::sendDragInfo(BaseClientProxy* newScreen)
 void
 Server::onMouseMoveSecondary(SInt32 dx, SInt32 dy)
 {
-       LOG((CLOG_DEBUG2 "onMouseMoveSecondary %+d,%+d", dx, dy));
+       LOG((CLOG_DEBUG1 "onMouseMoveSecondary %+d,%+d", dx, dy));
+       dx = dx / 2;
+       dy = dy / 2;
+       LOG((CLOG_DEBUG1 "Adjusted to %+d,%+d", dx, dy));

        // mouse move on secondary (client's) screen
        assert(m_active != NULL);
```

Now my host sends all movements reduced by half. Still, it is not correct, but at least it works much better.

**Comment by JohnSully** [comment]
@nbolton 

This is the main reason I had to stop using Synergy. I was an early adopter of 4K and this was problematic back in 2014 when I opened the bug and still is today.  I’ve subscribed to updates on this issue since that time hoping it would be addressed. 

My setup has changed a lot since 2014 but I still deal with mixed DPI all the time.

**Comment by samal84** [comment]
It's getting to the point where most high end laptops that IT professionals use have high dpi screens, so this is not a corner case any more.

**Comment by nbolton** [comment]
> I'm sure we'd fixed this.

Ah, I was mistakenly thinking of this issue: https://github.com/symless/synergy-core/issues/5648

This bug is now a very high priority on our backlog, and we'll take a look soon. Patches welcome.

**Comment by simon-clay** [comment]
Server on Mac mini with regular dpi monitor, client on windows surface with hidpi display at 200% - mouse is twice as slow on HiDPI client. Not a deal breaker, but, not ideal. License purchased today for WFH.

**Comment by roughwood** [comment]
Any updates on this issue? It's been a few months and this is still a daily struggle in my workflow.

**Comment by nbolton** [comment]
This is the highest priority issue on our backlog. We've been held up for a few weeks by some issues with our new CI system (Azure Pipelines) but @Jnewbon is pretty much finished with that fight. We'll do our very best to get the fix for this in the next update.

**Comment by yangshao** [comment]
@nbolton hi, how's the progress for this problem, i have the similar problem.

**Comment by epp-2k** [comment]
I just downloaded/installed Synergy today and this is still an issue - which version should contain the fix and when can we expect that to be released?

**Comment by Shkeats** [comment]
Yep me too from a 15" macbook pro host to a windows 10 connected to 4k tv.

**Comment by roughwood** [comment]
@nbolton Is this still the highest priority issue in the backlog? It's been several months since you've communicated that. Is there a plan to fix this bug and what is the timeline?

**Comment by ntrpnr** [comment]
Any progress here?

**Comment by johannchung** [comment]
Hi there, have been suffering from this for the longest time, even tried to upgrade to synergy Pro to see if that would resolve the issue (apparently not). Can we please have an update on progress? Thanks!

**Comment by yangshao** [comment]
Hi do you have some solution for this problem? it has been 6 years since this problem is proposed...

**Comment by roughwood** [comment]
Unfortunately it's looking like the solution is going to be to search for alternative software and stop recommending Synergy. I can't believe this isn't fixed yet.

**Comment by JakeHenry** [comment]
Really no excuse to not have this corrected yet. When developing this software, you'd think that would be one of the most basic unit tests that you'd run from the get go. Not a usable product until its fixed.

**Comment by rakki9999111** [comment]
This was the highest priority issue in your backlog in July 2020. 

It's now May 2021 and this is still an issue in build 1.13.1-stable-063519a8.

Setting aside the fact that this issue was opened in 2014....

Do you have an update for when this will be fixed?

**Comment by MK3Core** [comment]
Also very interested to see this fixed. Just purchased Pro for a work setup, and with one high DPI laptop client, the mouse speed is incredibly slow.

**Comment by Fluffball97** [comment]
Shame to see this dates back so far. My Windows laptop (server) is 3840x2160 and MacBook Pro (client) is 2560x1600, which is close enough to be useable, but mouse still moves faster than I'd like on the latter. For a one-size-fits-all solution I'd recommend what neworld said, adding a "scale" feature to adjust for any screen of differing DPI. Looking forward to a solution, eventually...

**Comment by brannanbholland** [comment]
Bump on this topic. Sad to say, I will be looking for an alternative if this is not resolved.

**Comment by LukeSkyw** [comment]
Have to pan the mouse twice to reach the corner of my screen. Anybody has a good alternative to Synergy?

**Comment by RayKoopa** [comment]
New version of Synergy still has this problem.
(Then again high DPI is trash on Windows anyway)

**Comment by CharyS117** [comment]
> Bump on this topic. Sad to say, I will be looking for an alternative if this is not resolved.

ShareMouse v6 beta just added separate mouse speed control.

**Comment by seanwitzke** [comment]
Is this fixed yet? 2014 and it's now almost 2022....

Just bought a 4K TV, and the mouse speed is atrocious.

**Comment by Lyn6969** [comment]
It's 2022, and I can't believe this bug still exists.

**Comment by KingScooty** [comment]
v3 Beta still seems to have this problem. Mouse sensitivity is really low on linked screens.

**Comment by desymless** [comment]
> v3 Beta still seems to have this problem. Mouse sensitivity is really low on linked screens.

We have implemented a fix for this issue, and it will be included in the next Synergy 3 Beta release 👍

**Comment by kevwkev** [comment]
@desymless Would you be able to provide an update on the fix. The latest release of Synergy 3.0.72 RC1 still have this issue.

**Comment by ELLIOTTCABLE** [comment]
Still having this here, RC as well. For me, both client and server are hiDPI - Windows is 6016×3384 at 225%, macOS on 3384×6016 at 200%.

Ideally, a configuration option to control mouse-speed scaling would be ideal; there's no guarantee that the pixel-ratios are even multiples of one-another, nor that it's specifically "200%" or "100%" on one (or either) device.

**Comment by leonardocustodio** [comment]
I just bought the software and I've the same issue, mouse is way slower in the client and there is no way to configure the mouse sensitivity.

**Comment by unv-unv** [comment]
Same issue on v3.0.76.5-rc3.

**Comment by desymless** [comment]
> Same issue on v3.0.76.5-rc3.

Hi 👋 

Would you mind trying the following and see if that helps?

1. Open Synergy 3
2. Go to Keyboard & Mouse and enable "Relative mouse moves" (if not enabled already)
3. Enable "Enable lock to screen"
4. Move to Secondary/Client computer, then use the scroll lock (scr lk) key to lock the cursor.
5. Check if mouse sensitivity has changed.

**Comment by unv-unv** [comment]
Yes, "Relative mouse moves" and "Enable lock to screen" were already enabled. I already played with "Relative mouse moves" with no effect, unfortunately.

**Comment by desymless** [comment]
> Yes, "Relative mouse moves" and "Enable lock to screen" were already enabled. I already played with "Relative mouse moves" with no effect, unfortunately.

I was hoping that would help, some customers have reported that when the cursor is locked on the client computer, the mouse sensitivity becomes corrected.

We are planning on adding a slider sensitivity option to Synergy 3, although that probably won't be included until v 3.2 (if not a later update).

**Comment by neworld** [comment]
> We are planning on adding a slider sensitivity option to Synergy 3

1.x version is open source, and I put a fix, which divided the movement vector by two. It works perfectly and feels natural. The slider option is even better and good enough for most cases.

**Comment by desymless** [comment]
> > We are planning on adding a slider sensitivity option to Synergy 3
> 
> 1.x version is open source, and I put a fix, which divided the movement vector by two. It works perfectly and feels natural. The slider option is even better and good enough for most cases.

That sounds very interesting, did you raise a PR (or create a fork) for that change? If so, do you have a link so I can share it with the developers?

**Comment by neworld** [comment]
> That sounds very interesting, did you raise a PR (or create a fork) for that change? If so, do you have a link so I can share it with the developers?

My solution was a dirty hack in the code without any user-adjustable settings. BTW, I made 2/3, but it was 50% the first time. Just one caveat: without floating numbers, I needed to make sure a 1 pixel movement would result in a 1 pixel client movement; for small movements, the mouse in the client does not move at all. It was very annoying. 

Patch itself I am using to this day: https://github.com/neworld/personal-aur-synergy/blob/master/trunk/adjust_low_dpi_mouse_speed.patch

**Comment by erikcagi** [comment]
Hi there,
Has this been solved? I am still experiencing the issue... the mouse sensitivity is completely different on clients computer. I have been using mouse without borders before, that had it solved but it was buggy and not launching all the time, thats why I purchased Synergy. 

Please if anyone has a solution for this - I would really appreciate it, thanks!

**Comment by Crmbl** [comment]
Hi, 

Still no update on this issue ? The mouse seems to be half the speed of the server.

I'm using Synergy v3.0.80.1-rc3, tried the 3.1.3 Beta and both failed to fix the issue.
Client screen has zoom 200% and screen resolution 3000x2000 (vs 2560x1440 no zoom)

Thank you for any update.

**Comment by nbolton** [comment]
> Still no update on this issue ?

Sorry, no update except to say that it's still on our radar and we plan to fix it.

**Comment by leonardocustodio** [comment]
Sounds like a Joke to say: "no update except that is on our radar" for an Issue that has been opened 10 YEARS ago.

**Comment by Crmbl** [comment]
Well, I prefer this than no input at all from the developper. I really like this software but using it with this issue is driving me nuts. 
Hopefully it will be fixed shortly.

**Comment by leonardocustodio** [comment]
I'm just saying I also really liked it, but this issue made it impossible to use, and I stopped; hopefully, they will fix it, and I can start using it again and even recommend it to others.

**Comment by nbolton** [comment]
> I'm just saying I also really liked it, but this issue made it impossible to use, and I stopped; hopefully, they will fix it, and I can start using it again and even recommend it to others.

Appreciate your passion for the app! I know it's been too long and I am sorry for the delay. This is due to being a small team and having to prioritise other problems.

**Comment by spurin** [comment]
Same problem sadly, using the latest paid version of Synergy Pro (3) on both Mac OS X and Windows. As I move the mouse cursor from Mac to Windows, it becomes slow and frustrating to use. Changes to mouse speed have no effect to the Synergy mouse (they work for a normal mouse).

@neworld's approach in the UI sounds like a really good idea. A slider or parameter that we can use to adjust both dx and dy would be perfect.

I tried ShareMouse as per one of the prior comments and this is as expected when the mouse speed is toggled. I don't really want to switch to this but, from a user experience it's currently better.

In the interim whilst this is being fixed, @neworld - do you have a windows client prebuilt that you can share?

@nbolton - Is it possible to combine the synergy open source client with the Pro version?

**Comment by nbolton** [comment]
@spurin Synergy 3 uses Synergy 1 (open source) at it's core so we just need to get @neworld's patch into the Synergy 1 code, and it'll become available in the next Synergy 3 update.

@neworld Would you mind opening a PR for this? We could perhaps use your patch and then add a feature flag to turn the hack on/off.

Re-surfacing [original patch](https://github.com/neworld/personal-aur-synergy/blob/master/trunk/adjust_low_dpi_mouse_speed.patch).
```diff
diff --git a/src/lib/server/Server.cpp b/src/lib/server/Server.cpp
index 2d7a2da..bc11104 100644
--- a/src/lib/server/Server.cpp
+++ b/src/lib/server/Server.cpp
@@ -1911,7 +1911,10 @@ Server::sendDragInfo(BaseClientProxy* newScreen)
 void
 Server::onMouseMoveSecondary(SInt32 dx, SInt32 dy)
 {
-	LOG((CLOG_DEBUG2 "onMouseMoveSecondary %+d,%+d", dx, dy));
+	LOG((CLOG_DEBUG1 "onMouseMoveSecondary %+d,%+d", dx, dy));
+	dx = dx - dx / 3;
+	dy = dy - dy / 3;
+	LOG((CLOG_DEBUG1 "Adjusted to %+d,%+d", dx, dy));
 
 	// mouse move on secondary (client's) screen
 	assert(m_active != NULL);
```

**Comment by spurin** [comment]
@nbolton whilst intentions were good, I've pretty much lost the afternoon trying to get a working Windows build environment for this. I use Windows for adhoc efforts and testing only, hence the desire to have the keyboard/mouse as a client in Synergy.

Are you able to please build an adhoc synergy-core windows binary with the Server.cpp patches mentioned? Would be very happy to test.

In the interim, this may satisfy some with this issue until it makes it's way to an upstream Synergy 3 Pro release.

**Comment by nbolton** [comment]
> I've pretty much lost the afternoon trying to get a working Windows build environment for this

I understand. Windows is the least fun OS to build on at the best of times. Sorry to hear about your frustration.

> Are you able to please build an adhoc synergy-core windows binary with the Server.cpp patches mentioned
> In the interim, this may satisfy some with this issue until it makes it's way to an upstream Synergy 3 Pro release.

Sounds like a plan. Stay tuned.

**Comment by spurin** [comment]
As per the request above, to get this hopefully moving in the right direction I've raised a Pull Request with @neworld's efforts, hopefully this can be used as the base for a feature flag allowing this to be turned off/on.

**Comment by Crmbl** [comment]
With the fix you provided the mouse speed will be slower. I hope that it will match your scenario, mine is reverse.
@nbolton do you plan to inject values to fine tune the feature (or maybe divider/multiplier) ? Or just a on/off flag.
Thanks for your replay

**Comment by spurin** [comment]
Thanks for highlighting this @Crmbl - indeed, this wasn't my intention, I also want to be able to fine tune this. At the moment I'm working in the background trying to get builds working for testing.

Something like the following may be a happy medium and is an area I was hoping to experiment with (I dont know enough about feature flags so was thinking about this with an environment variable for now) -

```
#include <cmath>    // For std::round

  const char* envVal = std::getenv("SYNERGY_MOUSE_ADJUSTMENT");
  if (envVal != nullptr) {
    try {
      double multiplier = std::stod(envVal); // Convert to double
      dx = static_cast<SInt32>(std::round(dx * multiplier)); // Apply multiplier and round
      dy = static_cast<SInt32>(std::round(dy * multiplier));
      LOG((CLOG_DEBUG1 "Adjusted to %+d,%+d using multiplier %.2f", dx, dy, multiplier));
    } catch (const std::exception& e) {
      // Handle error
      LOG((CLOG_ERROR "Invalid SYNERGY_MOUSE_ADJUSTMENT value: %s", envVal));
    }
  }
```

**Comment by spurin** [comment]
Good news, as per the pull request above, thanks to the original efforts of @neworld, I have been able to make a working prototype where we can adjust the speed of the mouse as desired via an environment variable at startup (speed up, or slow down - thanks again @Crmbl for the pointer on this).

@nbolton - appreciate all of the guidance on getting the automated CI in place, after some trial and error I was able to get this working and building artifacts that can be used.

For those who wish to try this out, you can pick up a build artefact from my personal fork. Example usage (using Mac OS X as a Server example), to double the speed of the mouse:

```
SYNERGY_MOUSE_ADJUSTMENT=2; open /Applications/Synergy.app
```

You can also slow it down -

```
SYNERGY_MOUSE_ADJUSTMENT=0.3; open /Applications/Synergy.app
```

I believe you need to be logged into Github to see the CI logs and to access artefacts - 

Whilst I'm using Mac OS X (Apple Silicon) for reasons I don't know, the ARM build doesn't work for me, however, the x64 one works fine, link: https://github.com/spurin/synergy/actions/runs/10837174328/artifacts/1926578591

Windows: https://github.com/spurin/synergy/actions/runs/10837174328/artifacts/1926581032

If you're on a Linux variant, access the main CI job @ https://github.com/spurin/synergy/actions/runs/10837174328 - choose your build/variant on the left hand side, expand the Upload job and look for the Artifact download URL.

Hope this helps and looking forward to seeing this as a finished feature both in Synergy community and Synergy 3 Pro 🚀

**Comment by Crmbl** [comment]
Thanks for your work ! I will definitely try this out on Windows, if anything differs I'll give feedback

**Comment by nbolton** [comment]
> @nbolton - appreciate all of the guidance on getting the automated CI in place, after some trial and error I was able to get this working and building artifacts that can be used.

You're very welcome! Great work.

**Comment by Crmbl** [comment]
I have not tested your fix yet, but I was wondering, with your fix, how this scenario will be handled:
- Server at 2560x1440 100%
- Client at 3000x2000 200% AND a connected screen at 2560x1440 100%

It will be like the server on the laptop screen (3K x 2K) but faster on the client connected screen if a make the mouse faster, right?
The "fix" would be to make the laptop as the server, and make the mouse speed slower to match, but it is not ideal.

Would it be possible to detect automatically the pixel density on the client screen AND on any connected screen to the client? Thus adapting the mouse speed accordingly.
I don't know if Synergy is able to detect the screens like screens, or it is a virtual desktop with a huge resolution (every resolutions added to make this "virtual desktop")

**Comment by nbolton** [comment]
Perhaps @neworld might have some insight here.

> Would it be possible to detect automatically the pixel density on the client screen AND on any connected screen to the client? Thus adapting the mouse speed accordingly.

That's a good idea. Unfortunately, right now Synergy detects all screens as one big screen, but there are plans to understand the individual screen resolutions.

**Comment by spurin** [comment]
On the Server.cpp code, if it was possible to view the client name in that chunk of code that we modified then technically I think we could check for an environment variable that includes the client name.

If this is possible then each client could have their own independent offset variable.

Then, later on, this could be transitioned to a client specific value.

Thoughts @nbolton ?

**Comment by Crmbl** [comment]
Well, it would be nice, surely, but what if the client have multiple screens with different pixel density.
It would require a variable for each screen for that specific client. And then Synergy would know on which screen the mouse is, which does not seems to be implemented right now

**Comment by nbolton** [comment]
> environment variable

I think env var was a good solution to get this testable. 

For those who are interested, test packages for PR #7511 are available for a limited time on: https://github.com/deskflow/deskflow/actions/runs/11001078547?pr=7511
