### ISSUE TITLE
Client process starts multiple times on Mac client

### ISSUE THREAD

**Issue by fogoat** [deskflow/deskflow#5408]
I restarted my Windows 7 32-bit workstation that is the Synergy server. After I log in, Synergy running as a service keeps giving this warning about my MacBookPro client is already connected. I can move the mouse back and forth between Mac and PC, but this loop of WARNING and NOTE goes on endlessly. Only way to stop is to quit the MacBookPro synergy client and restart it.

```
[2016-06-30T08:12:43] WARNING: a client with name "MacBookPro" is already connected
[2016-06-30T08:12:43] NOTE: disconnecting client "MacBookPro"
[2016-06-30T08:12:43] NOTE: client "MacBookPro" has disconnected
[2016-06-30T08:12:44] NOTE: accepted client connection
[2016-06-30T08:12:44] WARNING: a client with name "MacBookPro" is already connected
[2016-06-30T08:12:44] NOTE: disconnecting client "MacBookPro"
```

**Comment by henryptung** [comment]
Can confirm I'm running into the same problem. FWIW, I have a similar setup:
- Server: Win 8 x64, Synergy 1.7.6 (service)
- Client: Macbook Pro, El Capitan, Synergy 1.7.6

Log: https://gist.github.com/henryptung/fb322aac524dfb3f421328e0bd0fd839

Mine also contains some other oddities, like the SSL errors, invalid commands, and strange triple-connect behavior from the client (probably part of the client-already-connected problem).

Restarting Synergy Windows/server-side doesn't seem to help, and occasionally results in the stale-`synwinhk.dll`-handle issue in the log. At the bottom of the log, `synergys.exe` crashes, and my mouse becomes extremely unresponsive (think <1 fps update rate, almost completely unresponsive to clicks) so I have to struggle to actually confirm closure, at which point the mouse goes back to normal. Not quite sure what's going on there, but that crash is particularly challenging to recover from.

Restarting the Mac-side client did restore normal behavior (and it stops the strange triple-connect attempts in the log, so that seems a likely source of the "already connected" errors).

**Comment by amckee** [comment]
@sunk818 @henryptung 
Can you provide a process list from the client? I've only seen this when there are in fact two instances running. The first gets connected (hence the working cursor), the second gets rejected with the message that the client is already connected.

Please send the output of this (during the issue) to confirm:
`ps aux | grep -i synergy`

**Comment by sunk818** [comment]
@amckee You may be right as restarting the computer seems to take away this behavior. I didn't check for multiple processes, but seems like something synergy should be checking for anyway.

**Comment by henryptung** [comment]
@amckee Sorry for neglecting this bug for a while, but I haven't had much occasion to use it recently. Will post a process list the next time the bug recurs. Sorry for the delay!

**Comment by erikliland** [comment]
I am experiencing the same problem on my Mac. 
1. Synergy icon does not indicate "run"
2. Drop-down-menu is always indicating "Start", ("Stop" is inactive)
<img width="129" alt="skjermbilde 2016-10-14 kl 14 59 30" src="https://cloud.githubusercontent.com/assets/8565318/19388291/16faa0f0-921f-11e6-996e-3cec4a48d064.png">
3. If I click Start multiple times, I would end up with the problem in this issue. And the process list will look something like this:
![Uploading Skjermbilde 2016-10-14 kl. 15.06.23.png…]()

**Comment by CanadianJeff** [comment]
I just noticed this in 1.10.x

**Comment by nbolton** [comment]
@CanadianJeff Thanks for letting us know. Is your client computer a Mac? Are you seeing multiple client processes (`synergyc`) running like @erikliland?

**Comment by sunk818** [comment]
I have to do a `pkill synergy` and make sure they are all gone in Activity Monitor, I don't get the repeated log messages.

**Comment by koalahamlet** [comment]
For what it's worth, I'm definitely seeing this as well.

**Comment by koalahamlet** [comment]
I just fixed it locally. 

My fix was that I had to change the name of my client to something besides mhuff-dt-01. However before changing the name everything was configured correctly as per the setup instructions, so I think there's definitely something wonky going on. 
Anyway, hope this helps other people resolve their problems :)

**Comment by melek** [comment]
Just chiming in to say I experience this bug on occasion as well (Windows 10 server, Mac client). 

Quitting and restarting Synergy seems to work to resolve for me; I will leave Activity Monitor open to see if I can catch what steps might cause the bug to occur for me.

**Comment by ywiskerke** [comment]
Same here... 6yrs since it first was reported and it's still an issue on MacOS Monterey.

**Comment by CanadianJeff** [comment]
what an interesting issue bump that was started back in 2016? might as well close this and open up a new issue at this point

**Comment by hlslaughter** [comment]
Yeah, on Ubuntu 20 and 22, synergy starts three processes. Everything works, but it's annoying. I usually just kill 2 of them in the system tray so I don't have to look at them.

**Comment by ywiskerke** [comment]
@hlslaughter It's not just three processes... If I suspend a machine that is a client, the server will actually keep starting new instances. I've had up to 20 instances running after a day or two coming back to my desk.

**Comment by desymless** [comment]
Hi all,

Are you all seeing multiple instances of the Synergy user interface (GUI) or the core processes (ie. synergys and synergyc)?

And do you experience the same issue with Synergy 3 Beta?

**Comment by nbolton** [comment]
Hello all, does anyone see this in 1.15?

**Comment by sithlord48** [comment]
This only happens if the previous version of the gui crashed or was killed as we currently do not have a way for the gui to clean up the detached process we start.

**Comment by nbolton** [comment]
Yeah, I actually see this a lot in dev when my IDE kills the GUI (which does not terminate the client/server process).

I still think it's something we should solve somehow.

**Comment by sithlord48** [comment]
This should hopefully not happen anymore under normal circumstances. But if it crashes that is what the other issue is all about fixing
