### ISSUE TITLE
Unlocking a Windows Client with Lock Screen active or UAC prompt will move the mouse back to the server

### ISSUE THREAD

**Issue by oilcan-productions** [deskflow/deskflow#7899]
### Project

Deskflow

### Deskflow version number

1.7.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [X] I am unable to try the latest continuous build

### OS versions/distros

Windows 11 24H2

### Deskflow configuration

-Windows 11 Server
-Windows 11 Client
-Windows 11 Client

### What steps will reproduce the problem?

Start Deskflow and configure as server
Start Deskflow on the other 2 Windows 11 machines and configure as client
Enable TLS 
Make sure the Windows Client #1 is locked and needs a password to unlock
Move the mouse from the server to Client #1 
Click to dismiss the lock screen cover screen

Expected: the mouse cursor stays on client #1 and I can enter the PIN or password

Actual: the mouse cursor jumps back to the server and I have to move it back to the client to enter PIN and passcode

NOTE: the same happens when you get a UAC prompt. 

Navigate to client #2
Start a process that requires UAC for example 
right click the start button
select Windows Terminal (Administrator)

Expected: The UAC prompt to come up and the mouse cursor to stay on client #2 so I can click Yes

Actual: The UAC prompt comes up and the mouse cursor jumps back to the server, I have to navigate back to client #2 to click Yes.

### Log output

```shell
Server Log

[2024-11-15T11:35:36] DEBUG: active sides: 12
[2024-11-15T11:35:40] DEBUG: opening new socket: B561D8A0
[2024-11-15T11:35:40] DEBUG: openssl version: OpenSSL 3.3.1 4 Jun 2024
[2024-11-15T11:35:40] INFO: accepted secure socket
[2024-11-15T11:35:40] DEBUG: openssl cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
[2024-11-15T11:35:40] INFO: network encryption protocol: TLSv1.3
[2024-11-15T11:35:40] NOTE: accepted client connection
[2024-11-15T11:35:40] INFO: local languages: en, de
[2024-11-15T11:35:40] DEBUG: received client "Windows11-Client-#2" info shape=0,0 1920x1080 at 0,0
[2024-11-15T11:35:40] DEBUG: active sides: 12
[2024-11-15T11:35:40] NOTE: client "Windows11-Client-#2" has connected
[2024-11-15T11:35:44] INFO: switch from "Windows11-Server" to "Windows11-Client-#1" at 2559,901
[2024-11-15T11:35:44] INFO: leaving screen
[2024-11-15T11:35:44] DEBUG: open clipboard
[2024-11-15T11:35:44] DEBUG: close clipboard
[2024-11-15T11:35:44] DEBUG: ignored screen "Windows11-Server" update of clipboard 0 (unchanged)
[2024-11-15T11:35:44] DEBUG: open clipboard
[2024-11-15T11:35:44] DEBUG: close clipboard
[2024-11-15T11:35:44] DEBUG: ignored screen "Windows11-Server" update of clipboard 1 (unchanged)
[2024-11-15T11:35:44] DEBUG: dropped bogus delta motion: -1280,+176
[2024-11-15T11:35:45] INFO: switch from "Windows11-Client-#1" to "Windows11-Client-#2" at 813,14
[2024-11-15T11:35:45] DEBUG: sending clipboard 0 to "Windows11-Client-#2"
[2024-11-15T11:35:45] DEBUG: sent clipboard size=158
[2024-11-15T11:35:45] DEBUG: sending clipboard 1 to "Windows11-Client-#2"
[2024-11-15T11:35:45] DEBUG: sent clipboard size=158
[2024-11-15T11:35:47] DEBUG: tls connection closed
[2024-11-15T11:35:47] NOTE: client "Windows11-Client-#2" has disconnected
[2024-11-15T11:35:47] DEBUG: closing socket: B561D8A0
[2024-11-15T11:35:47] INFO: jump from "Windows11-Client-#2" to "Windows11-Server" at 1280,720
[2024-11-15T11:35:47] INFO: entering screen
[2024-11-15T11:35:47] DEBUG: active sides: 12
[2024-11-15T11:35:51] DEBUG: opening new socket: B5626600
[2024-11-15T11:35:51] DEBUG: openssl version: OpenSSL 3.3.1 4 Jun 2024
[2024-11-15T11:35:51] INFO: accepted secure socket
[2024-11-15T11:35:51] DEBUG: openssl cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
[2024-11-15T11:35:51] INFO: network encryption protocol: TLSv1.3
[2024-11-15T11:35:51] NOTE: accepted client connection
[2024-11-15T11:35:51] INFO: local languages: en, de
[2024-11-15T11:35:51] DEBUG: received client "Windows11-Client-#2" info shape=0,0 1920x1080 at 0,0
[2024-11-15T11:35:51] DEBUG: active sides: 12
[2024-11-15T11:35:51] NOTE: client "Windows11-Client-#2" has connected
```
Client #2 Log
```
[2024-11-15T11:35:41] WARNING: detected application not running, pid=29668
[2024-11-15T11:35:42] INFO: backing off, wait=2s, failures=1
[2024-11-15T11:35:44] INFO: starting new process
[2024-11-15T11:35:44] INFO: activeDesktop:Winlogon
[2024-11-15T11:35:44] INFO: starting new process
[2024-11-15T11:35:44] WARNING: failed to determine current keyboard layout
[2024-11-15T11:35:44] NOTE: started client
[2024-11-15T11:35:44] NOTE: connecting to 'IP.Sub.Net.160': IP.Sub.Net.160:24800
[2024-11-15T11:35:44] INFO: service status: active
[2024-11-15T11:35:44] NOTE: server fingerprint: Server Finger Print Redacted
[2024-11-15T11:35:44] INFO: connected to secure socket
[2024-11-15T11:35:44] INFO: server tls certificate info: /CN=Deskflow
[2024-11-15T11:35:44] INFO: network encryption protocol: TLSv1.3
[2024-11-15T11:35:44] INFO: local languages: en
[2024-11-15T11:35:44] INFO: remote languages: en, de
[2024-11-15T11:35:44] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: de
[2024-11-15T11:35:44] NOTE: connected to server
[2024-11-15T11:35:49] INFO: entering screen
[2024-11-15T11:35:49] INFO: clipboard was updated
[2024-11-15T11:35:49] INFO: clipboard was updated
[2024-11-15T11:35:51] INFO: leaving screen
[2024-11-15T11:35:51] WARNING: current secondary screen is entered on shutdown
[2024-11-15T11:35:51] NOTE: stopped client
[2024-11-15T11:35:51] WARNING: detected application not running, pid=30972
[2024-11-15T11:35:52] INFO: backing off, wait=2s, failures=1
[2024-11-15T11:35:54] INFO: starting new process
[2024-11-15T11:35:54] INFO: activeDesktop:Default
[2024-11-15T11:35:54] INFO: starting new process
[2024-11-15T11:35:54] NOTE: started client
[2024-11-15T11:35:54] NOTE: connecting to 'IP.Sub.Net.160': IP.Sub.Net.160:24800
[2024-11-15T11:35:54] INFO: service status: active
[2024-11-15T11:35:54] NOTE: server fingerprint: Server Finger Print Redacted
[2024-11-15T11:35:54] INFO: connected to secure socket
[2024-11-15T11:35:54] INFO: server tls certificate info: /CN=Deskflow
[2024-11-15T11:35:54] INFO: network encryption protocol: TLSv1.3
[2024-11-15T11:35:54] INFO: local languages: en
[2024-11-15T11:35:54] INFO: remote languages: en, de
[2024-11-15T11:35:54] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: de
[2024-11-15T11:35:54] NOTE: connected to server
[2024-11-15T11:38:51] INFO: entering screen
[2024-11-15T11:38:51] INFO: clipboard was updated
[2024-11-15T11:38:51] INFO: clipboard was updated
```
```


### Additional information

_No response_

**Comment by nbolton** [comment]
Yes, this a problem (and quite an annoying one). This is a symptom of how the core process is relaunched when Windows switches between [window sessions](https://stackoverflow.com/questions/4686897/sessions-window-stations-and-desktops). When you're at the login screen, Windows actually switches the current window session between two window sessions. Only processes launched in the current session can emulate input; hence the core process has to be relaunched.

Perhaps a more elegant approach would be to run multiple core process instances and switch which one is active based on the window session, then when the new core process takes over the input emulation, it can restore the mouse cursor position rather than it being sent back to the server. The networking for this might be a bit complicated, as ideally we wouldn't want to drop the connection between switching which core process is active.

**Comment by shrubba** [comment]
Just a quick mention, not sure if this will contribute or not.. 

I'm experiencing the same issue with DeskFlow (Recently installed to replace Synergy, like yesterday), where I have to manually login or authenticate the UAC via the physical machine. But with Synergy 1.14 (Under Win10), this was never experienced and was always able to login and deal with the UAC. 

So something in the Synergy code must be able to deal with this, and could be shared with DeskFlow?

**Comment by nbolton** [comment]
> So something in the Synergy code must be able to deal with this, and could be shared with DeskFlow?

Synergy is based on Deskflow, so it's likely to be a new bug, which affects both.

**Comment by sithlord48** [comment]
When a UAC prompt happens the users is Admin.  Normal windows behavior :(

**Comment by sithlord48** [comment]
This maybe solved by https://github.com/deskflow/deskflow/pull/8194

**Comment by sithlord48** [comment]
Also the UAC problem here should be resolved by #8180  , closing as such

**Comment by nbolton** [comment]
I believe this is still a problem; when the process is restarted (Windows needs this to elevate the process).

Perhaps you could try the "Always" elevate option under the Windows service settings in Preferences.
