### ISSUE TITLE
Deskflow on MacOS does not respect swapped Control and Command keys.

### ISSUE THREAD

**Issue by ZehCastro** [deskflow/deskflow#8388]
### Project

Deskflow

### Deskflow version info

Windows Deskflow 1.17.0+r1 (download + install)
MacOS Deskflow 1.2.0.1 (via brew)

### Build type

Community package (apt, dnf, brew, etc.)

### Operating systems (OS)

- [x] Windows
- [x] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [x] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows 11
- MacOS 15.3.1

### Deskflow configuration

-Windows 11 Server, MacOS 15.3.1 Client

### What steps will reproduce the problem?

1. invert control and command keys on MacOS (see https://www.macinstruct.com/tutorials/how-to-switch-the-control-and-command-keys/)
2. connect mac to windows server
3. notice windows key still acts as command and control still acts control.

### Log output

```shell

```

**Comment by sithlord48** [comment]
That is a known issue in 1.17.0 should be fixed in 1.18 or 1.19 don't recall the exact version.

**Comment by ZehCastro** [comment]
I'll try updating.

**Comment by ZehCastro** [comment]
Update the PC side:

Deskflow: 1.20.1.0 (bc96ddeb)
Qt: 6.8.2
System: Windows 11 Version 23H2

Still seeing the issue.

**Comment by ZehCastro** [comment]
Just found the per-client settings screen witch has settings for modifier keys.

![Image](https://github.com/user-attachments/assets/24f26f59-e8d2-401f-b485-ba1fa86ed152)

No idea which is which thou. Perhaps Super/Meta should also include whatever they are called on the proprietary platforms?

Will test changing those and report back.

**Comment by sithlord48** [comment]
That is the dialog you would change it on for any client. 
iirc Alt is command and crtl is control

**Comment by ZehCastro** [comment]
Poking around those will solve the issue.

**Comment by dreadedhamish** [comment]
In barrier and input-leap the setting you need are:
Ctrl: Super
Meta: None
Super: Ctrl
This doesn't work in deskflow, noe does any other combination.

**Comment by ZehCastro** [comment]
My initial test was using deskflow on both sides (windwos server + Mac client), CTRL+C / CTRL+V (remapped so, actually Command+C/Command+V) worked, which was my main blocker.

Further tests showed that some other key combos do not work. E.g.: Command + Right/Left arrow to cycle between fullscreen windows.

**Comment by nbolton** [comment]
> This doesn't work in deskflow, noe does any other combination.

@sithlord48 Have you experienced this bug?

**Comment by sithlord48** [comment]
I have had no issues with modifier mapping since the key swap was fixed in 1.19.0 (or was it 1.18) .. I use those combos all the time as have a few full screen windows on the mac always, the only thing i could think of is maybe ZehCastro was hit w/ a stuck modifier when trying the combo

**Comment by Copperfie1d** [comment]
I have solved this problem, perhaps you can refer to it. My keyboard is on Windows, and when switching to Mac, Ctrl is control, win is option, and alt is command, which solves my keyboard habit on Mac computers. This is the configuration on the Mac screen:

![Image](https://github.com/user-attachments/assets/673d65d7-b8fa-4463-93e8-b60f324b0d33)
