### ISSUE TITLE
When switching display windows with the mouse, it requires moving twice to switch successfully.

### ISSUE THREAD

**Issue by JayHsu5** [deskflow/deskflow#8786]
### Project

Deskflow

### Deskflow version info

Deskflow : 1.23.0

### Operating systems (OS)

- [x] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows 10 22H2
- Windows 11 10.0.22621

### Deskflow configuration

-  Windows 10 22H2 server,  Windows 11 10.0.22621 client
-  Windows 11 10.0.22621 left , Windows 10 22H2 right

### What steps will reproduce the problem?

The server is running Windows 10 22H2, and the client is running Windows 11 10.0.22621. When switching display windows with the mouse, it requires moving twice to switch successfully.

### Log output

```shell

```

**Comment by nbolton** [comment]
Could you try the latest [continuous](https://github.com/deskflow/deskflow/releases/tag/continuous) build?

**Comment by JayHsu5** [comment]
> Could you try the latest [continuous](https://github.com/deskflow/deskflow/releases/tag/continuous) build?

Using latest version 1.23.0.13 (49e36cfd), the "moving twice" issue has been resolved; however, there is a new problem where two mouse cursors appear when moving a window on the server side.

**Comment by nbolton** [comment]
> two mouse cursors appear

This is a first for me. Could you send a screenshot or take a picture with your camera phone?

**Comment by sithlord48** [comment]
Are we still seeing this with the current continuous (1.24.343) @JayHsu5  ?
