### ISSUE TITLE
Right Alt (AltGr) key combinations incorrectly transmitted as `Ctrl+Alt` instead of special characters

### ISSUE THREAD

**Issue by colenio-mhe** [deskflow/deskflow#8864]
### Project

Deskflow

### Deskflow version info

Deskflow: 1.23.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [x] Windows
- [x] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [x] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [x] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows 11
- macOS 15.6

### Deskflow configuration

- Windows 11 Server with EurKEY, macOS Client with EurKEY

### What steps will reproduce the problem?

1. Set up **Windows 11 (server)** with EurKEY layout.  
2. Connect **macOS (client)** using Deskflow.  
3. On the mac client, press `Right Alt + o` or `Right Alt + u`.  
4. Observe that a system/application shortcut is triggered and only a plain letter is entered instead of the special character.  

### Log output

```shell

```

### Additional information

I’m experiencing an issue with **Deskflow** where the `Right Alt` (AltGr) key is no longer working as expected.  

I use the **EurKEY layout** on both Windows (server) and macOS (client). Normally, pressing `Right Alt + o` should produce `ö`, and `Right Alt + u` should produce `ü`...  

However, since today Deskflow transmits the input as:  

- `Right Alt + o` → `Ctrl+Alt+o` → results in a shortcut on macOS and then inserts a plain `o`  
- `Right Alt + u` → triggers Teams’ *jump to unread messages* shortcut and then inserts a plain `u`  
- ....

So instead of sending the special character, it is treating `Right Alt` as `Ctrl+Alt`.  
Does anyone have an idea what changed ?

## Additional Notes
- This worked before with the same setup.  Just today suddenly it started to behave like this.
- No deskflow update or config changes were made before the issue appeared. 
- I tried older versions and the newest continuous build, behaviour stayed.
- As a test, I switched back to **InputLeap on Windows (server)** with Deskflow on macOS (client), and the problem disappears — special characters (`öäüß`) work correctly again.

**Comment by sithlord48** [comment]
Is this a duplicate of #8839 ?

**Comment by colenio-mhe** [comment]
Honestly I’m not sure if its the same problem.  
The most confusing part for me is that it worked 100% fine on Friday, but when I turned everything back on today it just started misbehaving.  

Nothing was updated or changed over the weekend — the devices weren’t even powered on — so it feels like it broke “out of nowhere.”

**Comment by sithlord48** [comment]
That is very odd something had to have changed

**Comment by colenio-mhe** [comment]
Just to clarify: I’m not aware of any config change.  
It’s possible Windows Update might have done something in the background, but I did not update Deskflow or changed any settings.

Important notes:  
- I do **not** sync keyboard language (never did). Turning it on doesn’t help either.  
- Current setup where it works again:  
  - **Input Leap 3.0.2** (Windows Server)  
  - **Deskflow 1.23.0** (macOS Client)  

---

### Logs

Client Log if AltGr is pressed and InputLeap is Server
```
[2025-08-18T15:21:20] DEBUG1: keystrokes:
[2025-08-18T15:21:20] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=down client=0x0000
[2025-08-18T15:21:20] DEBUG1: recv key down id=0x0000efea, mask=0x2006, button=0x0138
[2025-08-18T15:21:20] DEBUG1: active server language is empty
[2025-08-18T15:21:20] DEBUG1: key down translated to id=0x0000efec, mask=0x2012
[2025-08-18T15:21:20] DEBUG1: mapKey efec (61420) with mask 2012, start state: 0002, group: 1
[2025-08-18T15:21:20] DEBUG1: could not found requested language
[2025-08-18T15:21:20] DEBUG1: best key index 1 of 1 (exact)
[2025-08-18T15:21:20] DEBUG1: found key in group 1
[2025-08-18T15:21:20] DEBUG1: state: 0002,0000,0000
[2025-08-18T15:21:20] DEBUG1: flip: 0000 (0002 vs 0000 in 0000 - 0000)
[2025-08-18T15:21:20] DEBUG1: desired state: 2012 0002,0000,0000
[2025-08-18T15:21:20] DEBUG1: flip: 0000 (0002 vs 2012 in ffef - 6020)
[2025-08-18T15:21:20] DEBUG1: mapped to 038, new state 0012
[2025-08-18T15:21:20] DEBUG1: keystrokes:
[2025-08-18T15:21:20] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=down client=0x0000
[2025-08-18T15:21:20] DEBUG1: recv key up id=0x0000efe3, mask=0x2004, button=0x001d
[2025-08-18T15:21:20] DEBUG1: key up translated to id=0x0000efe3, mask=0x2010
[2025-08-18T15:21:20] DEBUG1: new state 0010
[2025-08-18T15:21:20] DEBUG1: keystrokes:
[2025-08-18T15:21:20] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=up client=0x0000
[2025-08-18T15:21:20] DEBUG1: recv key up id=0x0000efea, mask=0x2000, button=0x0138
[2025-08-18T15:21:20] DEBUG1: key up translated to id=0x0000efec, mask=0x2000
[2025-08-18T15:21:20] DEBUG1: new state 0000
[2025-08-18T15:21:20] DEBUG1: keystrokes:
[2025-08-18T15:21:20] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=up client=0x0000
```

ClientLog if AltGr is pressed and Deskflow is Server 
```
[2025-08-18T15:23:58] DEBUG1: keystrokes:
[2025-08-18T15:23:58] DEBUG1: skipping keystroke, language sync is disabled
[2025-08-18T15:23:58] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=down client=0x0000
[2025-08-18T15:23:58] DEBUG1: recv key down id=0x0000efea, mask=0x2006, button=0x0138, lang="en"
[2025-08-18T15:23:58] DEBUG1: key down translated to id=0x0000efec, mask=0x2012
[2025-08-18T15:23:58] DEBUG1: mapKey efec (61420) with mask 2012, start state: 0002, group: 1
[2025-08-18T15:23:58] DEBUG1: language en has group id 0
[2025-08-18T15:23:58] DEBUG1: best key index 1 of 1 (exact)
[2025-08-18T15:23:58] DEBUG1: found key in group 0
[2025-08-18T15:23:58] DEBUG1: language en has group id 0
[2025-08-18T15:23:58] DEBUG1: state: 0002,0000,0000
[2025-08-18T15:23:58] DEBUG1: flip: 0000 (0002 vs 0000 in 0000 - 0000)
[2025-08-18T15:23:58] DEBUG1: desired state: 2012 0002,0000,0000
[2025-08-18T15:23:58] DEBUG1: flip: 0000 (0002 vs 2012 in ffef - 6020)
[2025-08-18T15:23:58] DEBUG1: mapped to 038, new state 0012
[2025-08-18T15:23:58] DEBUG1: keystrokes:
[2025-08-18T15:23:58] DEBUG1: skipping keystroke, language sync is disabled
[2025-08-18T15:23:58] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=down client=0x0000
[2025-08-18T15:23:59] DEBUG1: recv key up id=0x0000efe3, mask=0x2004, button=0x001d
[2025-08-18T15:23:59] DEBUG1: key up translated to id=0x0000efe3, mask=0x2010
[2025-08-18T15:23:59] DEBUG1: new state 0010
[2025-08-18T15:23:59] DEBUG1: keystrokes:
[2025-08-18T15:23:59] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=up client=0x0000
[2025-08-18T15:23:59] DEBUG1: recv key up id=0x0000efea, mask=0x2000, button=0x0138
[2025-08-18T15:23:59] DEBUG1: key up translated to id=0x0000efec, mask=0x2000
[2025-08-18T15:23:59] DEBUG1: new state 0000
[2025-08-18T15:23:59] DEBUG1: keystrokes:
[2025-08-18T15:23:59] DEBUG1:   button=0x0038 virtualKey=0x0037 keyDown=up client=0x0000
```

Maybe the Logs help. I really wish I could provide more details..

**Comment by sithlord48** [comment]
> [2025-08-18T15:23:58] DEBUG1: skipping keystroke, language sync is disabled 

do you have the option on the client to use the server language ?

**Comment by colenio-mhe** [comment]
Both systems use English.

Mac is English UK.
Windows English Germany.

Both systems use EurKey maps.

If I enable language sync on client(Mac) input method will switch to ISO US but the weird behaviour will not stop. 

Logs will say that en is language on client and server. 

Btw thanks for your help, much appreciated 🙏

**Comment by 4our4ace** [comment]
I'm having the same conversion without any configuration or anything.
AltGr is sent from Windows Server to Linux Client:
First sent as Control_L when keydown
When a combination is pressed, like AltGr + A, then Alt_L is added.
Tested with "xev" on Ubuntu with x11

**Comment by sithlord48** [comment]
This should be solved for wayland clients with 1.23.0.145 (current [continuous](https://github.com/deskflow/deskflow/releases/tag/continuous))

**Comment by nbolton** [comment]
I suppose we could tentatively close as maybe fixed by one of these PRs:
- #8860
- #8881

If this is not fixed for anyone, please let us know and we can reopen.

**Comment by sithlord48** [comment]
can you check the list of https://github.com/deskflow/deskflow/issues/8450 to see if any others maybe fixed by this also ?

**Comment by colenio-mhe** [comment]
No luck for me on Win (Server) to Mac (Client) nothing changed at all.

(It still woks by using InputLeap on Server side (win))

**Comment by MartinK99** [comment]
Still an issue using 
Deskflow: 1.24.0.0 (56a1bd68)
Qt: 6.9.1
System: macOS 26.0 
for both the client and server with the following client logs:
```
[2025-09-17T10:17:28] DEBUG1: recv key down id=0x0000efe3, mask=0x0002, button=0x001d, lang="en"
[2025-09-17T10:17:28] DEBUG1: mapKey efe3 (61411) with mask 0002, start state: 0000, group: 0
[2025-09-17T10:17:28] DEBUG1: language en has group id 0
[2025-09-17T10:17:28] DEBUG1: best key index 1 of 1 (exact)
[2025-09-17T10:17:28] DEBUG1: found key in group 0
[2025-09-17T10:17:28] DEBUG1: state: 0000,0000,0000
[2025-09-17T10:17:28] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2025-09-17T10:17:28] DEBUG1: desired state: 0002 0000,0000,0000
[2025-09-17T10:17:28] DEBUG1: flip: 0000 (0000 vs 0002 in fffd - 6020)
[2025-09-17T10:17:28] DEBUG1: mapped to 03c, new state 0002
[2025-09-17T10:17:28] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=down client=0x0000
[2025-09-17T10:17:28] DEBUG1: recv key down id=0x0000efea, mask=0x0006, button=0x0138, lang="en"
[2025-09-17T10:17:28] DEBUG1: mapKey efea (61418) with mask 0006, start state: 0002, group: 0
[2025-09-17T10:17:28] DEBUG1: language en has group id 0
[2025-09-17T10:17:28] DEBUG1: best key index 1 of 1 (exact)
[2025-09-17T10:17:28] DEBUG1: found key in group 0
[2025-09-17T10:17:28] DEBUG1: state: 0002,0000,0000
[2025-09-17T10:17:28] DEBUG1: flip: 0000 (0002 vs 0000 in 0000 - 0000)
[2025-09-17T10:17:28] DEBUG1: desired state: 0006 0002,0000,0000
[2025-09-17T10:17:28] DEBUG1: flip: 0000 (0002 vs 0006 in fffb - 6020)
[2025-09-17T10:17:28] DEBUG1: mapped to 03b, new state 0006
[2025-09-17T10:17:28] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=down client=0x0000
[2025-09-17T10:17:28] DEBUG1: recv key up id=0x0000efe3, mask=0x0004, button=0x001d
[2025-09-17T10:17:28] DEBUG1: new state 0004
[2025-09-17T10:17:28] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=up client=0x0000
[2025-09-17T10:17:28] DEBUG1: recv key up id=0x0000efea, mask=0x0000, button=0x0138
[2025-09-17T10:17:28] DEBUG1: new state 0000
[2025-09-17T10:17:29] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=up client=0x0000
```
... Interestingly enough, @colenio-mhe's suggestion did _not_ work for me, and I got nearly the same behaviour (same client, replaced deskflow server with input-leap server)
```
[2025-09-17T12:00:39] DEBUG1: recv key down id=0x0000efe3, mask=0x0002, button=0x001d
[2025-09-17T12:00:39] DEBUG1: active server language is empty
[2025-09-17T12:00:39] DEBUG1: mapKey efe3 (61411) with mask 0002, start state: 0000, group: 0
[2025-09-17T12:00:39] DEBUG1: could not found requested language
[2025-09-17T12:00:39] DEBUG1: best key index 1 of 1 (exact)
[2025-09-17T12:00:39] DEBUG1: found key in group 0
[2025-09-17T12:00:39] DEBUG1: state: 0000,0000,0000
[2025-09-17T12:00:39] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2025-09-17T12:00:39] DEBUG1: desired state: 0002 0000,0000,0000
[2025-09-17T12:00:39] DEBUG1: flip: 0000 (0000 vs 0002 in fffd - 6020)
[2025-09-17T12:00:39] DEBUG1: mapped to 03c, new state 0002
[2025-09-17T12:00:39] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=down client=0x0000
[2025-09-17T12:00:39] DEBUG1: recv key down id=0x0000efea, mask=0x0006, button=0x0138
[2025-09-17T12:00:39] DEBUG1: active server language is empty
[2025-09-17T12:00:39] DEBUG1: mapKey efea (61418) with mask 0006, start state: 0002, group: 0
[2025-09-17T12:00:39] DEBUG1: could not found requested language
[2025-09-17T12:00:39] DEBUG1: best key index 1 of 1 (exact)
[2025-09-17T12:00:39] DEBUG1: found key in group 0
[2025-09-17T12:00:39] DEBUG1: state: 0002,0000,0000
[2025-09-17T12:00:39] DEBUG1: flip: 0000 (0002 vs 0000 in 0000 - 0000)
[2025-09-17T12:00:39] DEBUG1: desired state: 0006 0002,0000,0000
[2025-09-17T12:00:39] DEBUG1: flip: 0000 (0002 vs 0006 in fffb - 6020)
[2025-09-17T12:00:39] DEBUG1: mapped to 03b, new state 0006
[2025-09-17T12:00:39] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=down client=0x0000
[2025-09-17T12:00:41] DEBUG1: recv key up id=0x0000efe3, mask=0x0004, button=0x001d
[2025-09-17T12:00:41] DEBUG1: new state 0004
[2025-09-17T12:00:41] DEBUG1:   button=0x003c virtualKey=0x003b keyDown=up client=0x0000
[2025-09-17T12:00:41] DEBUG1: recv key up id=0x0000efea, mask=0x0000, button=0x0138
[2025-09-17T12:00:41] DEBUG1: new state 0000
[2025-09-17T12:00:41] DEBUG1:   button=0x003b virtualKey=0x003a keyDown=up client=0x0000
[2025-09-17T12:00:45] DEBUG1: recv mouse down id=1
```
Nearly the same logs as well, the only difference being the missing language info

**Comment by colenio-mhe** [comment]
> Interestingly enough, [@colenio-mhe](https://github.com/colenio-mhe)'s suggestion did _not_ work for me, and I got nearly the same behaviour (same client, replaced deskflow server with input-leap server)

Did you make sure that the Deskflow service wasn’t running on Windows? It seems important that only the InputLeap service is active.

Other than that, I’m afraid I don’t have any ideas.

**Comment by MartinK99** [comment]
> Did you make sure that the Deskflow service wasn’t running on Windows? It seems important that only the InputLeap service is active.

Yes, all other services (Deskflow, Barrier) were disabled manually. I was also surprised to not see the same keystroke logs in line 1,2 as you did, with DEBUG1 enabled, and what makes it work on your end might be `skipping keystroke, language sync is disabled`, which feels more like a coincidence based on language settings/keyboard layouts/etc. This doesn't appear in my case, so the client has no reason not to execute both keystrokes. In any case, the server is not supposed to send two strokes in the first place in my opinion, so that has to be checked first.
Here's input-leap logs (hopefully the same as deskflow):
```
[2025-09-18T11:21:28] DEBUG1: hook: 0x000000a2 0x221d0001
[2025-09-18T11:21:28] DEBUG1: hook: 0x60a20000 0x221d0001
[2025-09-18T11:21:28] DEBUG1: hook: 0x70a20000 0x221d0001
[2025-09-18T11:21:28] DEBUG1: event: Key char=0, vk=0xa2, nagr=0, lParam=0x221d0001
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0000
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0002
[2025-09-18T11:21:28] DEBUG1: hook: 0x000000a5 0x21380001
[2025-09-18T11:21:28] DEBUG1: hook: 0x500000a5 0x21380001
[2025-09-18T11:21:28] DEBUG1: hook: 0x60a50000 0x21380001
[2025-09-18T11:21:28] DEBUG1: hook: 0x71a50000 0x21380001
[2025-09-18T11:21:28] DEBUG1: event: Key char=0, vk=0xa5, nagr=1, lParam=0x21380001
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0002
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0006
[2025-09-18T11:21:28] DEBUG1: onKeyDown id=61411 mask=0x0002 button=0x001d
[2025-09-18T11:21:28] DEBUG1: send key down to "MOB-J57XQVVP4R" id=61411, mask=0x0002, button=0x001d
[2025-09-18T11:21:28] DEBUG1: onKeyDown id=61418 mask=0x0006 button=0x0138
[2025-09-18T11:21:28] DEBUG1: send key down to "MOB-J57XQVVP4R" id=61418, mask=0x0006, button=0x0138

[2025-09-18T11:21:28] DEBUG1: hook: 0x000000a2 0x821d0001
[2025-09-18T11:21:28] DEBUG1: hook: 0x60a20000 0x821d0001
[2025-09-18T11:21:28] DEBUG1: hook: 0x70a20000 0x821d0001
[2025-09-18T11:21:28] DEBUG1: event: Key char=0, vk=0xa2, nagr=0, lParam=0x821d0001
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0006
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0004
[2025-09-18T11:21:28] DEBUG1: hook: 0x000000a5 0x81380001
[2025-09-18T11:21:28] DEBUG1: hook: 0x60a50000 0x81380001
[2025-09-18T11:21:28] DEBUG1: hook: 0x70a50000 0x81380001
[2025-09-18T11:21:28] DEBUG1: event: Key char=0, vk=0xa5, nagr=0, lParam=0x81380001
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0004
[2025-09-18T11:21:28] DEBUG1: new mask: 0x0000
[2025-09-18T11:21:28] DEBUG1: onKeyUp id=61411 mask=0x0004 button=0x001d
[2025-09-18T11:21:28] DEBUG1: send key up to "MOB-J57XQVVP4R" id=61411, mask=0x0004, button=0x001d
[2025-09-18T11:21:28] DEBUG1: onKeyUp id=61418 mask=0x0000 button=0x0138
[2025-09-18T11:21:28] DEBUG1: send key up to "MOB-J57XQVVP4R" id=61418, mask=0x0000, button=0x0138
```

**Comment by sithlord48** [comment]
This maybe fixed for wayland servers with 1.24.0.343. Try with deskflow server / client if you can just incase its an issue we have fixed that input-leap still has.

**Comment by colenio-mhe** [comment]
I’ve found some new details that might explain the behavior.

On my Mac I remap **left Alt → Super** and **Super → Alt**, since the Command key is right next to the spacebar and this layout works better for me. It turns out this remapping also affects the **right Alt** key in some way.

<img width="122" height="173" alt="Image" src="https://github.com/user-attachments/assets/79ee997a-e681-4a33-9908-9e45e88973d4" />

With this custom mapping enabled, Deskflow seems to treat the right Alt key as a mix of Super and Alt, which leads to the strange behavior I’m seeing. When I revert to the default macOS modifier layout and let **language sync** choose a different keymap (not EurKey on macOS), all keys work normally.

For comparison, InputLeap appears to handle left/right Alt separately and doesn’t support the “keyboard sync” keymap switching at all — and in my case, that actually results in more predictable behavior.

So it looks like Deskflow may be interpreting or merging the modifier remaps differently, especially for the right Alt key.

| macOS Setup                    | Windows Setup        | Remapped Modifier Keys | Result                                               |
|--------------------------------|-----------------------|-------------------------|------------------------------------------------------|
| Deskflow (any standard keymap) | Deskflow (EurKey)     | No                      | Works (adds ü on AltGr + U press)                    |
| Deskflow (EurKey)              | Deskflow (EurKey)     | No                      | Doesn’t work (adds ü *and* u on AltGr + U press)     |
| Deskflow (any standard keymap or EurKey) | Deskflow (EurKey)     | Yes                     | Doesn’t work (invokes Cmd+U and sends u on AltGr+U)  |
| Deskflow (EurKey)              | InputLeap (EurKey)    | Yes                     | Works (adds ü on AltGr + U press)                    |

On the server (windows side), the newest continuous build of Deskflow was running.

**Comment by krisrok** [comment]
DeskFlow Linux  -> DeskFlow Windows also does not correctly transfer Right Alt + ß (backslash) or Right Alt + Q (@) to the client. Instead, nothing happens. Both use German layout. Everything else seems to work fine though.

Using v1.25.0 on both sides.
