### ISSUE TITLE
Deskflow appears to delay Windows reboot and appears as Asian characters until program terminates

### ISSUE THREAD

**Issue by derekschrock** [deskflow/deskflow#9013]
### Sanity checks

- [ ] I have done the sanity checks, and my issue persists
- [x] These sanity checks are not relevant to the bug

### Deskflow version info

Deskflow: 1.24.0
System: Windows 11 25H2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [x] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Deskflow configuration

- Windows 11 client
- macOS 15.7.1 server
- macOS bottom, Windows top

### What steps will reproduce the problem?

- Using Windows 11 Deskflow as a client (continually reconnecting) to a server macOS 15.7.1 (Deskflow 1.24.0) 
- Reboot Windows 11 machine with Deskflow in the background.

### Log output

```shell

```

### Additional information

I can't absolutely pin this down to Desktop flow however all the evidence seems to point to it.

When rebooting Windows 11 with since 1.24.0 (installed via github msi and winget update) about 75% of the time when I reboot I'll see the below message.  While this is normal sometimes to see Windows waiting for things to close the asian text draw my attention.  Translations did help much however some pointed to possible encoding issues where unicode data was mishandled and printed as incorrect characters.

As this reddit and stackoverflow article suggests piping it thru iconv might help.

https://www.reddit.com/r/translator/comments/1hi69ko/comment/m2wlz1j/?context=3&share_id=8aOzbQ48yjaFHJc-2sIxM&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1

https://superuser.com/questions/1040822/this-app-is-preventing-you-from-restarting-app-name-in-random-chinese-charact

```
$ echo '孜歲汦睯' | iconv -t utf-16le
\[rkflow
```

\[rkflow ~= Deskflow ?

That was the first sign as a possible link to Deskflow.

Next if the dialog appeared during reboot, hitting cancel and going to Task Manager deskflow core and daemon were still running.  Trying a restart directly after and ~99% of the time the same dialog would appear.  Hit cancel repeat.   End task'ing the deskflow processes then restarting the dialog would never reappear.

Then third in Event Viewer I can see `... preventing the system from shutting down ... ` events with deskflow bin names.

I can't reproduce this  continuous portable however I can't get Windows 11 continuous to connect to macOS server.  This might be a different issue.

![Image](https://github.com/user-attachments/assets/25687513-6cbc-480f-82db-fb40a9289d2d)

**Comment by sithlord48** [comment]
Since this is fixed in continuous this bug is solved. If you have other issue try asking on irc or matrix for help with the connection issue.

**Comment by a4840639** [comment]
I am still seeing this on the latest contineous build and I have to say the gibberish name is extremely scary

**Comment by sithlord48** [comment]
@nbolton  can you look in to this when you get some time please.

**Comment by Raven-Lunatic** [comment]
I was using the Windows version 1.26.0 having this same issue at shutdown. 

It was quite alarming, thought I had been h4x0r3d lol
