### ISSUE TITLE
Press and hold of Keys (Backspace, Arrow Keys, Any key and type) not working?  V1.25.0.33 Continuous

### ISSUE THREAD

**Issue by AKSKMY** [deskflow/deskflow#9233]
### Sanity checks

- [x] I have done the sanity checks, and my issue persists
- [ ] These sanity checks are not relevant to the bug

### Deskflow version info

Deskflow: 1.25.0.33 (fd94403a)
Qt: 6.10.0
System: Windows 11 Version 24H2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [x] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Deskflow configuration

1. One side windows 11 Pro another Windows 11 Enterprise

### What steps will reproduce the problem?

1. Normal Start of Deskflow
2. Press and hold down any key
3. Eg Backspace it does not delete all the way but instead register back one time only.

### Log output

```shell
No logs relevant
```

### Additional information

1. Changing back to barrier works normally no issues.
2. Changing back to Deskflow V1.25 for client fixes it.

**Comment by sithlord48** [comment]
Must be related to the hold fixes we did on #9217. Looks like we may need to not do this on windows. Thank you for your report.

**Comment by AKSKMY** [comment]
> Must be related to the hold fixes we did on [#9217](https://github.com/deskflow/deskflow/pull/9217). Looks like we may need to not do this on windows. Thank you for your report.

I see I'll revert just the client back to V1.25.0 stable for now. At first I thought it was my network issue...

On a very side note is there a bug with the language changing function? It seems to randomly change when I change screens.

**Comment by sithlord48** [comment]
There have been various user reports of keymap issues.

**Comment by sithlord48** [comment]
I made a PR  #9234 to fix the windows regression caused by #9217 . If you would like to test it you can try the build once the [action](https://github.com/deskflow/deskflow/actions/runs/19795139278) finishes (about 15 - 20 minutes from now)

https://github.com/deskflow/deskflow/actions/runs/19795139278/artifacts/4715929973 <- direct link to the build for win64

**Comment by AKSKMY** [comment]
> I made a PR [#9234](https://github.com/deskflow/deskflow/pull/9234) to fix the windows regression caused by [#9217](https://github.com/deskflow/deskflow/pull/9217) . If you would like to test it you can try the build once the [action](https://github.com/deskflow/deskflow/actions/runs/19795139278) finishes (about 15 - 20 minutes from now)
> 
> https://github.com/deskflow/deskflow/actions/runs/19795139278/artifacts/4715929973 <- direct link to the build for win64

oo ok will try later. Thanks!

As for the keyboard language random bug swopping is it fixed here as well?

Edit: Works. Can press and hold down keystrokes now.

**Comment by sithlord48** [comment]
No just the repeat regression

**Comment by HattDroid** [comment]
The artifact is not available to download anymore and unfortunately this issue is still present on the last Continuous v1.25.0.146 or Stable 1.25.0 (Windows server, Linux client).

**Comment by sithlord48** [comment]
@HattDroid  please paste info about your client here. 


just tested 1.25.0.146 as client in both X11(KDE) and Wayland (KDE)  and key repeat seams to work just fine.  (linux server)

**Comment by HattDroid** [comment]
> [@HattDroid](https://github.com/HattDroid) please paste info about your client here.
> 
> just tested 1.25.0.146 as client in both X11(KDE) and Wayland (KDE) and key repeat seams to work just fine. (linux server)

Thanks for the quick follow-up.

The Linux client is currently running over Barrier 2.4.0 release. Shall I try to find a way to merge it to a Deskflow set up maybe?

**Comment by sithlord48** [comment]
Yes the client has the Error so yes you should be using a deskflow client to resolve this

**Comment by HattDroid** [comment]
Thanks for the advice and help @sithlord48 ! 👍
I'll revert to Barrier as server as the solution, as the Linux client can't have deskflow built or installed because of dependency reasons and flatpak also not being an option.

Edit: Used Input Leap instead of Barrier for the server and this is working perfectly.
